#!/usr/bin/env ruby -w

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Opt out of sending analytics data about usage to fastlane servers
opt_out_usage

# ============= Lanes ================

platform :android do
    desc "Download and overwrite metadata"
    lane :fetch_metadata do
      METADATA_PATH = "./metadata/"
      sh "rm -rf " + METADATA_PATH
      sh "fastlane supply init -m " + METADATA_PATH
    end
  
    desc "Update metadata for the application on Google Play Store"
    lane :update_metadata do
      deploymentTrack = "production"
      version_code = get_version_from_google_playstore(deploymentTrack)
  
      # Validate meta data update
      validate_metadata_update = false
  
      upload_to_play_store(
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_changelogs: true,
        track: deploymentTrack,
        version_code: version_code,
        release_status: "draft",
        timeout: 3600,
        validate_only: validate_metadata_update,
      )
      puts "Android update_metadata lane completed ✅"
    end
  end
  
  # ------------------------------ Utils ------------------------------
  def get_version_from_google_playstore(deploymentTrack)
    versions = google_play_track_version_codes(track: deploymentTrack)
    return versions[0]
  end
  